### ISSUE TITLE
Error in "predictions = multi_atlas_vae_model.predict_labels(return_pandas=True)"

### ISSUE THREAD

**Issue by zhang0730** [WanluLiuLab/scAtlasVAE#1]
**following the "(Part I) Integration, cross-atlas comparison, and transfer learning"
when I ran to the Cross-atlas integration and the code below**

import umap 
adata_cd8_zheng_2021_merged.obsm['X_gex'] = multi_atlas_vae_model.get_latent_embedding()
adata_cd8_zheng_2021_merged.obsm['X_umap'] = umap.UMAP().fit_transform(adata_cd8_zheng_2021_merged.obsm['X_gex'])

predictions = multi_atlas_vae_model.predict_labels(return_pandas=True)
predictions_logits = multi_atlas_vae_model.predict_labels(return_pandas=False)

**the error message：**
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[20], line 2
      1 # 7. 获取预测结果并存储到 adata.uns 和 adata.obs 中
----> 2 predictions = multi_atlas_vae_model.predict_labels(return_pandas=True) #报错 需要调试代码：将改为浮点数
      3 predictions_logits = multi_atlas_vae_model.predict_labels(return_pandas=False)
      5 # 存储预测结果

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/scatlasvae/model/_gex_model.py:1506, in scAtlasVAE.predict_labels(self, n_per_batch, return_pandas, show_progress)
   1504     X, _, batch_index, _, _, _, _ = self._prepare_batch(batch_indices)
   1505 else:
-> 1506     X, _, batch_index, _, _, _, _ = future.result()
   1508 if e+1 < len(X):
   1509     future = executor.submit(self._prepare_batch, X[e+1])

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/_base.py:437, in Future.result(self, timeout)
    435     raise CancelledError()
    436 elif self._state == FINISHED:
--> 437     return self.__get_result()
    439 self._condition.wait(timeout)
    441 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/thread.py:57, in _WorkItem.run(self)
     54     return
     56 try:
---> 57     result = self.fn(*self.args, **self.kwargs)
     58 except BaseException as exc:
     59     self.future.set_exception(exc)

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/scatlasvae/model/_gex_model.py:1798, in scAtlasVAE._prepare_batch(self, batch_indices)
   1796 def _prepare_batch(self, batch_indices):
   1797     P = None
-> 1798     batch_data = self._dataset[batch_indices.cpu().numpy()]
   1799     batch_index, label_index, additional_label_index, additional_batch_index = None, None, None, None
   1801     if self.low_memory_initialization:

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by Beiusxzw** [comment]
Please install an updated version of scAtlasVAE via:
```
pip install scatlasvae==1.0.5.8或者pip install –upgrade scatlasvae
```
This should fix the issue. Feel free to reach me again if the issue persists.

**Comment by zhang0730** [comment]
thanks, it worked
