### ISSUE TITLE
Error:module 'scatlasvae.tools' has no attribute 'transfer_umap'

### ISSUE THREAD

**Issue by zhang0730** [WanluLiuLab/scAtlasVAE#2]
**run to the "Query-to-reference mapping to pan-disease CD8 T atlas" with code belowed:**
adata_transfer.obsm["X_umap"] = scatlasvae.tl.transfer_umap(
    adata_cd8.obsm["X_gex"],
    adata_cd8.obsm["X_umap"],
    adata_transfer.obsm["X_gex"],
    method="knn",
    n_neighbors=3,
)["embedding"]

**the error message:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[33], line 1
----> 1 adata_transfer_tex.obsm["X_retrain_umap"] = scatlasvae.tl.transfer_umap(
      2     adata_cd8_tex.obsm["X_retrain_GEX"],
      3     adata_cd8_tex.obsm["X_retrain_umap"],
      4     adata_transfer_tex.obsm["X_retrain_GEX"],
      5     method="knn",
      6     n_neighbors=3,
      7 )["embedding"]
      9 adata_transfer_tex.obs["cell_subtype_4"] = vae_model_transfer.predict_labels(
     10     return_pandas=True
     11 )["cell_subtype_4"]

AttributeError: module 'scatlasvae.tools' has no attribute 'transfer_umap'

**can i use code below instead?**
adata_transfer.obsm['X_umap'] = umap.UMAP().fit_transform(adata_transfer.obsm['X_gex'])

**Comment by Beiusxzw** [comment]
please replace `scatlasvae.tl.transfer_umap` with `scatlasvae.tl.umap_alignment`. Sorry for the inconvenience due to the un-updated version of the documentation.

**Comment by zhang0730** [comment]
Thanks for your kind help. you are always helpful. haha
