### ISSUE TITLE
Can scAtlasVAE be used for batch effect removal in any cell type? 

### ISSUE THREAD

**Issue by fancy112233** [WanluLiuLab/scAtlasVAE#4]
Can scAtlasVAE be used for batch effect removal in any cell type? For instance, can it be applied to epithelial cells or stromal cells like fibroblasts? Are there any special considerations when applying scAtlasVAE to non-CD8+ T cell data?

**Comment by Beiusxzw** [comment]
There would be no additional considerations. scAtlasVAE can be applied to other cell types for batch effect removal just like scVI, scPoli, etc...
