### ISSUE TITLE
Error in "predictions = multi_atlas_vae_model.predict_labels(return_pandas=True) "

### ISSUE THREAD

**Issue by zhang0730** [WanluLiuLab/scAtlasVAE#6]
**I am running the across atlas integration of my own data and secceed in initializing a merge_data scAtlasVAE model.
after training and getting latent embedding, I would like to predict labels,
but I meet a ERROR attached below:**

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[97], line 2
      1 # 7. 获取预测结果并存储到 adata.uns 和 adata.obs 中
----> 2 predictions = multi_atlas_vae_model.predict_labels(return_pandas=True) 
      3 predictions_logits = multi_atlas_vae_model.predict_labels(return_pandas=False)

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/scatlasvae/model/_gex_model.py:1507, in scAtlasVAE.predict_labels(self, n_per_batch, return_pandas, show_progress)
   1505     X, _, batch_index, _, _, _, _ = self._prepare_batch(batch_indices)
   1506 else:
-> 1507     X, _, batch_index, _, _, _, _ = future.result()
   1509 if e+1 < len(X):
   1510     future = executor.submit(self._prepare_batch, X[e+1])

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/_base.py:437, in Future.result(self, timeout)
    435     raise CancelledError()
    436 elif self._state == FINISHED:
--> 437     return self.__get_result()
    439 self._condition.wait(timeout)
    441 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

File ~/mambaforge/envs/scatlasvae/lib/python3.8/concurrent/futures/thread.py:57, in _WorkItem.run(self)
     54     return
     56 try:
---> 57     result = self.fn(*self.args, **self.kwargs)
     58 except BaseException as exc:
     59     self.future.set_exception(exc)

File ~/mambaforge/envs/scatlasvae/lib/python3.8/site-packages/scatlasvae/model/_gex_model.py:1799, in scAtlasVAE._prepare_batch(self, batch_indices)
   1797 def _prepare_batch(self, batch_indices):
   1798     P = None
-> 1799     batch_data = self._dataset[batch_indices.cpu().numpy().astype(int)]
   1800     batch_index, label_index, additional_label_index, additional_batch_index = None, None, None, None
   1802     if self.low_memory_initialization:

IndexError: index 142053 is out of bounds for axis 0 with size 22387

could you tell me which part of the code should I re-debug?
millions of thanks!

**Comment by Beiusxzw** [comment]
Could you print the version of your current installation via `import scatlasvae; print(scatlasvae.__version__)`
And use to upgrade to the latest version
```
pip install scatlasvae==1.0.5.8 or pip install –upgrade scatlasvae
```

**Comment by zhang0730** [comment]
my version has been to 1.0.5.8.
import scatlasvae
print(scatlasvae.__version__)
1.0.5.8

**Comment by Beiusxzw** [comment]
Please try `pip install –upgrade scatlasvae` to upgrade to 1.0.5.9 and try to run `predict_labels`. This should solve the problem.  Sorry for bugs in the previous version

**Comment by zhang0730** [comment]
thanks. it works

**Comment by zhang0730** [comment]
> Please try `pip install –upgrade scatlasvae` to upgrade to 1.0.5.9 and try to run `predict_labels`. This should solve the problem. Sorry for bugs in the previous version

thanks. it works
